import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { Sidebar } from "@/components/shared/Sidebar";
import { Logout } from "@/components/shared/LogoutButton";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout principal
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <div className="grid grid-cols-[minmax(0,_1fr)_minmax(0,_5fr)] min-h-screen">
          <Sidebar />
          <main className="flex flex-col">
            <header className="flex-none">
              <Logout />
            </header>
            <div className="flex-grow">
              {children}
            </div>
          </main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
